### ISSUE TITLE
TypeError: 'BlockHash' object is not subscriptable

### ISSUE THREAD

**Issue by sliceme** [SuperteamDAO/solathon#50]
Code: 
```
from solathon.core.instructions import transfer
from solathon import Client, Transaction, PublicKey, Keypair

client = Client("https://api.devnet.solana.com")

sender = Keypair.from_private_key("....")
receiver = PublicKey("....")

instruction = transfer(
    from_public_key=sender.public_key,
    to_public_key=receiver, 
    lamports=100
)

transaction = Transaction(instructions=[instruction], signers=[sender])

result = client.send_transaction(transaction)
print("Transaction response: ", result)
```

Traceback : 
```
>>> result = client.send_transaction(transaction)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abc/Library/Python/3.9/lib/python/site-packages/solathon/client.py", line 626, in send_transaction
    recent_blockhash = blockhash_resp["result"]["value"]["blockhash"]
TypeError: 'BlockHash' object is not subscriptable
```

**Comment by GitBolt** [comment]
Thanks for opening the issue. It has been identified and fixed now. Re-install your package and you should be good to go!
