### ISSUE TITLE
Error with method client.get_token_accounts_by_owner(pk, mint_id)

### ISSUE THREAD

**Issue by grsoratoor** [SuperteamDAO/solathon#53]
Traceback (most recent call last):
  File "\solathon-test\main.py", line 23, in <module>
    r = c.get_token_accounts_by_owner("7pq8H6iY2TTTwW7Y5RBqoTNc46mZrN1JAar9ErqXpHfR",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\solathon-test\venv\Lib\site-packages\solathon\client.py", line 541, in get_token_accounts_by_owner
    response = self.build_and_send_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\solathon-test\venv\Lib\site-packages\solathon\client.py", line 587, in build_and_send_request
    raise RPCRequestError(f"Failed to fetch data from RPC endpoint. Error {res['error']['code']}: {res['error']['message']}")

solathon.utils.RPCRequestError: Failed to fetch data from RPC endpoint. Error -32602: Invalid parameters: **Expected from 2 to 3 parameters.**

when I removed line no: 547 in client.py, this method worked fine. (removed commitment from parameters as this RPC call accepts only 2 to 3 parameters)

**Comment by grsoratoor** [comment]
@GitBolt mentioning for getting notified

**Comment by GitBolt** [comment]
Thanks for raising the issue! Bug has been fixed now. Re-install the latest version of the package and you should be good to go @grsoratoor.

Let me know if its fine for you now, will close the issue then.

**Comment by grsoratoor** [comment]
Thank you @GitBolt, it is working fine now.
