### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Panda-2009** [SuperteamDAO/solathon#61]
Traceback (most recent call last):
  File "sollong_test.py", line 9, in <module>
    from solathon import Keypair
  File "/usr/local/lib/python3.8/dist-packages/solathon/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python3.8/dist-packages/solathon/client.py", line 5, in <module>
    from .utils import RPCRequestError, validate_commitment
  File "/usr/local/lib/python3.8/dist-packages/solathon/utils.py", line 6, in <module>
    from solathon.core.types import Commitment, RPCErrorType, RPCResponse
  File "/usr/local/lib/python3.8/dist-packages/solathon/core/types/__init__.py", line 1, in <module>
    from .account_info import AccountInfo, AccountInfoType, ProgramAccount, ProgramAccountType
  File "/usr/local/lib/python3.8/dist-packages/solathon/core/types/account_info.py", line 3, in <module>
    class AccountInfoType(TypedDict):
  File "/usr/local/lib/python3.8/dist-packages/solathon/core/types/account_info.py", line 12, in AccountInfoType
    data: Union[str, dict[str, Any]]
TypeError: 'type' object is not subscriptable

Env： Linux racknerd-63e53c 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
solathon               0.1.9  

test code：--------------------
async def sign():
    print('sign')

if __name__ == '__main__':
##########签到
    asyncio.run(sign())

**Comment by GitBolt** [comment]
What is your Python verison @Panda-2009?

**Comment by GitBolt** [comment]
issue was fixed. feel free to reopen if you face the problem again
