### ISSUE TITLE
Invalid response from RPC endpoint. Expected types dict | list | str, got int

### ISSUE THREAD

**Issue by monkeydp** [SuperteamDAO/solathon#67]
`client.get_minimum_balance_for_rent_exemption(44)`

```
Traceback (most recent call last):
  File "D:\project\local\solana-py\solana.py", line 19, in <module>
    result = client.get_minimum_balance_for_rent_exemption(44)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\Anaconda\Lib\site-packages\solathon\client.py", line 474, in get_minimum_balance_for_rent_exemption
    return self.build_and_send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\Anaconda\Lib\site-packages\solathon\client.py", line 745, in build_and_send_request
    raise RPCRequestError(
solathon.utils.RPCRequestError: Invalid response from RPC endpoint. Expected types dict | list | str, got int
```

**Comment by GitBolt** [comment]
Hey @monkeydp, thanks for informing! I just pushed fix for this. You can re-install the latest release of the package and it should work. If you face any problems, then feel free to re-open this issue.
