### ISSUE TITLE
error TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by l-arkadiy-l** [SuperteamDAO/solathon#83]
When I import package like `import solathon` I get this problem:
 ```
 File "/Users/a1234/PycharmProjects/money_maker/3.py", line 1, in <module>
    from solathon import Client
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/__init__.py", line 3, in <module>
    from .client import Client
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/client.py", line 5, in <module>
    from .utils import RPCRequestError, validate_commitment
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/utils.py", line 6, in <module>
    from solathon.core.types import Commitment, RPCErrorType, RPCResponse
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/core/types/__init__.py", line 1, in <module>
    from .account_info import AccountInfo, AccountInfoType, ProgramAccount, ProgramAccountType
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/core/types/account_info.py", line 3, in <module>
    class AccountInfoType(TypedDict):
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/core/types/account_info.py", line 12, in AccountInfoType
    data: Union[str, dict[str, Any]]
TypeError: 'type' object is not subscriptable
```

**Comment by GitBolt** [comment]
Hey @l-arkadiy-l, what is your Python version?

**Comment by l-arkadiy-l** [comment]
I tried 3.8 and 3.13

**Comment by bro34674** [comment]
I have the same problem
python 3.8


Need add
`from typing import Dict`
and replace all **dict** to **Dict** ?

**Comment by l-arkadiy-l** [comment]
When i replace all dict to Dict I get another error:

```
Traceback (most recent call last):
  File "/Users/a1234/PycharmProjects/money_maker/solathon1.py", line 1, in <module>
    from solathon.core.instructions import transfer
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/__init__.py", line 3, in <module>
    from .client import Client
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/client.py", line 5, in <module>
    from .utils import RPCRequestError, validate_commitment
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/utils.py", line 6, in <module>
    from solathon.core.types import Commitment, RPCErrorType, RPCResponse
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/core/types/__init__.py", line 35, in <module>
    class RPCResponse(TypedDict):
  File "/Users/a1234/PycharmProjects/money_maker/.venv/lib/python3.8/site-packages/solathon/core/types/__init__.py", line 38, in RPCResponse
    result: Union[Result[T], T]
TypeError: '_TypedDictMeta' object is not subscriptable
```

**Comment by GitBolt** [comment]
Hey @l-arkadiy-l and @66696e656c696665 
I have fixed these issues and published the new version. Please re-install the package, test it, and let me know if it works!

**Comment by GitBolt** [comment]
Note: Python 3.9 is the minimum compatible version now
